### ISSUE TITLE
Not getting the data inside the csv files

### ISSUE THREAD

**Issue by Subharanjan2055** [mr-sherman/sarif-to-csv#3]
@mr-sherman while integrating with my workflow its generating the csv files but there is no data inside the csv files . could you please assist me .

**Comment by Subharanjan2055** [comment]
@mr-sherman

**Comment by mr-sherman** [comment]
Can you provide the .sarif file?

**Comment by mr-sherman** [comment]
@Subharanjan2055

**Comment by Subharanjan2055** [comment]
@mr-sherman will it convert FOR GHES ?

**Comment by mr-sherman** [comment]
It should. I'm thinking maybe there has been an update to sarif, that's why I'd just like to debug with your file, if you can.  If not, I can try to generate a new sarif with my own projects, but I'd rather just debug it with yours to see why it's not populating the CSV.

**Comment by mr-sherman** [comment]
Can reproduce it with my own project - I'll investigate and fix.  Thanks for the heads up, sorry it took me a while to get to this.

**Comment by Subharanjan2055** [comment]
Okay thanks @mr-sherman

**Comment by Subharanjan2055** [comment]
@mr-sherman again its not generating any data. could you please check.

**Comment by mr-sherman** [comment]
@Subharanjan2055 fixed the issue.  Github actions-generated .sarif files should render a correct .csv now.  Use v2.1

**Comment by Subharanjan2055** [comment]
@mr-sherman till now i was using for exporting results & i would like to say its amazing . As per the requirement can we get the all the state like as of now we are getting while exporting sarif to csv is open only like that can we get all the states i.e closed, dismissed etc .

**Comment by mr-sherman** [comment]
@Subharanjan2055 - I'm not seeing the states attribute in the sarif.  I'm getting SARIF from running the codeQL CLI or via the CodeQL github action, and it doesn't contain any alert status about them being dismissed or open or closed, or anything.  This is because it's a fresh scan and no one has interacted with the results yet. 

 How are you getting your SARIF?  via the Security Dashboard API or something?   If you share with me a sample or tell me how you're obtaining your SARIF I should be able to fix.

Thanks,

**Comment by Subharanjan2055** [comment]
@mr-sherman by running CodeQL github actions am generating SARIF & after converting into csv the only attribute am getting is Name , severity , score , Tags & source here i want to add one more attribute i.e state open ,close & dismissed .

Thanks,

**Comment by Subharanjan2055** [comment]
@mr-sherman Any update on this ?

Thanks,

**Comment by mr-sherman** [comment]
@Subharanjan2055  - I've been thinking on how best to accomplish this.  Right now, the data in the csv comes directly from the sarif file that is generated by an analysis.  It doesn't know anything about the status of the vulnerabilities, which ones got closed, which ones are new, etc.  That's all done after the sarif is sent to GitHub's security dashboard.  The security dashboard keeps track of the status.

In order to get statuses like "closed, open, dismissed", I would have to make an API call to GitHub's security dashboard, pull the vulnerability information  and then generate the .csv.  I have to develop an option to pull the SARIF from the file or pull the SARIF from the API and generate the CSV accordingly.

**Comment by Subharanjan2055** [comment]
Hi @mr-sherman ,

I hope this email finds you well. I am writing to bring to your attention a query we have regarding the CSV reports generated by our system.

We have been using this action from 2022 and it has proven to be immensely beneficial for us. However, we have encountered a slight inconvenience regarding the visibility of line numbers alongside alerts in the CSV reports.

As you may know, the GitHub dashboard displays alerts based on line numbers, which assists us greatly in identifying and addressing vulnerabilities. However, the CSV reports currently do not include line numbers alongside alerts, causing some difficulty when sharing reports with clients.

Therefore, we kindly request if it would be possible to include line numbers with alerts in the source section of the CSV format. This adjustment would greatly enhance the usability of the reports and streamline our vulnerability management process.

Your assistance in this matter would be highly appreciated and would significantly contribute to the efficiency of our operations. If you require any further information or clarification regarding this request, please do not hesitate to contact us.

Thank you for your attention to this matter, and we look forward to your positive response.

Warm regards,
Subhranjan2055

**Comment by Subharanjan2055** [comment]
@mr-sherman just a gentle reminder!!

Thanks,
Subh

**Comment by Subharanjan2055** [comment]
@mr-sherman

 reminder!!!

Thanks,
Subha

**Comment by mr-sherman** [comment]
Sorry @Subharanjan2055  - I will add line numbers.  Can you create a separate issue for this so it can be tracked?
